version: '3.8'
services:
  database:
    container_name: database
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${database_user}
      - POSTGRES_PASSWORD=${database_password}
      - POSTGRES_DB=${database_name}
    # Saving data to a real location is strongly suggested
    #volumes:
    # - /location:/var/lib/postgresql/data
  seq:
    container_name: seq
    image: datalust/seq
    restart: unless-stopped
    ports:
      - ${seq_port}:80
    environment:
      - ACCEPT_EULA=${seq_accept_eula}
    # Saving data to a real location is strongly suggested
    #volumes:
    # - /location:/data
  eru:
    container_name: eru
    build: .
    restart: unless-stopped
    ports:
    - ${eru_port}:80
    depends_on:
      - database
    environment:
      - DOTNET_ENVIRONMENT=docker
      - Database__Type=postgresql
      - Database__AutomaticallyMigrate=${database_automatic_migrations}
      - Database__ConnectionString=Host=database;Database=${database_name};Username=${database_user};Password=${database_password}
      - UploadKey=${upload_key}
      - Admins__0__Username=admin
      - Admins__0__Password=s@mpl3P@ssword
      - CultureSettings__DefaultCulture=${default_culture}
    # Saving data to a real location is strongly suggested
    #volumes:
    # - /location:/Logs