site_name: eru
theme:
   name: readthedocs
nav:
   - 'Home': index.md
   - 'Contribution': contribution.md
   - 'Config': config.md
   - 'Deployment': 
      - 'Build from source': build-from-source.md
      - 'Docker': docker.md
   - 'Communication': 
      - 'Facebook Messenger':
         - 'Open Beta': facebook-messenger-open-beta.md