site_name: eru
theme:
   name: readthedocs
nav:
   - 'Home': index.md
   - 'Contribution': contribution.md
   - 'Config': config.md
   - 'Deployment': 
      - 'Build from source': build-from-source.md
      - 'Docker': docker.md
   - 'Communication': 
      - 'Facebook Messenger':
         - '[EN/PL] What about release': messenger/what-about-release.md
         - '[EN] Open Beta': messenger/facebook-messenger-open-beta-en.md
         - '[PL] Open Beta': messenger/facebook-messenger-open-beta-pl.md