name: Main CI/CD Pipeline

on: 
  push:
  pull_request:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 3.1
      - name: Clean
        run: dotnet clean --configuration Release && dotnet nuget locals all --clear
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
  build_and_push_docker:
    name: Publishes docker image into repository.
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
      - name: Push docker image to GHCR.io
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          registry: ghcr.io
          name: xxlo-devs/eru
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PASSWORD }}
          tag_names: true